#!/bin/bash

echo "📱 Phone Access Configuration Complete!"
echo ""
echo "✅ Changes Made:"
echo ""
echo "1. ✅ Updated CLIENT_URL to: http://192.168.1.13:5173"
echo "2. ✅ Configured Vite to listen on 0.0.0.0 (all interfaces)"
echo "3. ✅ Configured Backend to listen on 0.0.0.0"
echo "4. ✅ Updated CORS to accept your IP address"
echo ""
echo "🚀 Next Steps:"
echo ""
echo "1. Restart the servers:"
echo "   cd /Users/nikhil/Desktop/lms"
echo "   npm run dev"
echo ""
echo "2. Wait for both servers to start:"
echo "   ✅ Backend:  http://0.0.0.0:5000"
echo "   ✅ Frontend: http://0.0.0.0:5173"
echo ""
echo "3. On your Mac, access:"
echo "   🖥️  http://localhost:5173  (or http://192.168.1.13:5173)"
echo ""
echo "4. Login as admin:"
echo "   📧 Email: admin@lms.com"
echo "   🔑 Password: admin123"
echo ""
echo "5. Send a NEW teacher invitation"
echo "   (Old invitations still have localhost links)"
echo ""
echo "6. The email will now have:"
echo "   ✅ http://192.168.1.13:5173/register/teacher/..."
echo ""
echo "7. Open this link on your phone!"
echo "   Make sure your phone is on the SAME WiFi network"
echo ""
echo "📱 Testing from Phone:"
echo ""
echo "Before clicking the invitation link, test if you can reach the server:"
echo ""
echo "On your phone's browser, go to:"
echo "   http://192.168.1.13:5173"
echo ""
echo "You should see the LMS login page!"
echo ""
echo "If you see 'Connection Refused':"
echo "   - Check: Is your phone on the same WiFi as your Mac?"
echo "   - Check: Are the servers running?"
echo "   - Check: Is Mac firewall blocking connections?"
echo ""
echo "🔥 Mac Firewall Check (if needed):"
echo "   System Settings → Network → Firewall"
echo "   Make sure it's not blocking Node/connections"
echo ""
echo "✅ Everything is configured! Just restart the servers and test!"
echo ""
